// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neqlnrnmdurljduhyutb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lcWxucm5tZHVybGpkdWh5dXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjYxMTUsImV4cCI6MjA2NTMwMjExNX0.35H8e6Ii6w1b_6rmha0BLOBvFFRTnqMVyWqsQtu4JXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);